name: Build IPA (No Signing)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter clean
      - run: flutter pub get

      # 🔥 تعطيل التوقيع داخل المشروع
      - name: Disable Code Signing
        run: |
          sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = "";/' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = .*;/PROVISIONING_PROFILE_SPECIFIER = "";/' ios/Runner.xcodeproj/project.pbxproj

      - name: Build IPA (No Codesign)
        run: flutter build ipa --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/ipa/*.ipa
