name: Build IPA (No Signing)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Show Flutter Version
        run: flutter --version

      - name: Flutter Clean
        run: flutter clean

      - name: Get Dependencies
        run: flutter pub get

      - name: Build IPA (No Codesign)
        run: flutter build ipa --release --no-codesign

      - name: Search for IPA
        run: |
          echo "Searching for IPA file..."
          find . -name "*.ipa"

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: "**/*.ipa"
